### ISSUE TITLE
Feature request: Support for Rich Text Format

### ISSUE THREAD

**Issue by lively-ops** [CrossCopy/tauri-plugin-clipboard#11]
Thank you for the awesome plugin. It would be perfect if you could add formatted text/rtf format as well.

**Comment by HuakunShen** [comment]
@lively-ops I wanted to add this as well, but for now I don't have an idea how to achieve it. 

Any suggestions?

**Comment by HuakunShen** [comment]
Electron's clipboard APIs seems to come from this file https://github.com/electron/electron/blob/main/shell/common/api/electron_api_clipboard.cc

But I am unable to find the depdency files.

Will look into this when I got time.

**Comment by lively-ops** [comment]
I think we will have to use winapi and cocoa crate for macOS and Windows and x11 or wayland libraries for linux. 

For cross-platform support we can use conditional compilation to include platform-specific code.

**Comment by lively-ops** [comment]
For Windows, found these in winapi crate:
https://docs.rs/winapi/latest/winapi/um/winuser/fn.SetClipboardData.html
https://docs.rs/winapi/latest/winapi/shared/wtypes/struct.userCLIPFORMAT.html
https://docs.rs/winapi/latest/winapi/um/winuser/fn.SetClipboardData.html
https://docs.rs/winapi/latest/winapi/um/winuser/fn.RegisterClipboardFormatW.html
https://docs.rs/winapi/latest/winapi/um/winuser/fn.RegisterClipboardFormatA.html

**Comment by HuakunShen** [comment]
I will work on this. Just got clipboard files working.

**Comment by ChurchTao** [comment]
> Electron's clipboard APIs seems to come from this file https://github.com/electron/electron/blob/main/shell/common/api/electron_api_clipboard.cc
> 
> But I am unable to find the depdency files.
> 
> Will look into this when I got time.

The API of electron is called chromium at the bottom level.

https://source.chromium.org/chromium/chromium/src/+/main:ui/base/clipboard/clipboard_mac.mm;l=276

I recently planned to use rust to write a low-level library similar to the Electron clipboard API, which is related to the low-level system API calls mentioned above.

**Comment by ChurchTao** [comment]
To be honest, the arboard library is not particularly well written, and no one is maintaining it. I am going to write one myself.

**Comment by HuakunShen** [comment]
> To be honest, the arboard library is not particularly well written, and no one is maintaining it. I am going to write one myself.

Thanks! Let me know when you write it, I am happy to change the clipboard dependency.

**Comment by ChurchTao** [comment]
@HuakunShen 
I have already built the library, but it is still under development. macOS has been developed, and I am currently developing Windows and Linux. Can you please take a look at my API first? I estimate that I will complete it in about a month, and I hope that listen to other people's opinions

https://github.com/ChurchTao/clipboard-rs

**Comment by HuakunShen** [comment]
@ChurchTao Great, I will take a look. Thanks!
