### ISSUE TITLE
Using in react useEffect lifecycle method freezes and locks the window

### ISSUE THREAD

**Issue by heysupratim** [CrossCopy/tauri-plugin-clipboard#17]
```
import { UnlistenFn } from "@tauri-apps/api/event";
import { useEffect } from "react";
import {
  onImageUpdate,
  onTextUpdate,
  startListening,
} from "tauri-plugin-clipboard-api";

const ImagesView = () => {
  let unlistenImageUpdate: UnlistenFn | null = null;
  let unlistenTextUpdate: UnlistenFn | null = null;
  let unlistenClipboard: (() => Promise<void>) | null = null;

  useEffect(() => {
    async function listenerSetup() {
      unlistenClipboard = await startListening();
      unlistenImageUpdate = await onImageUpdate((b64Str) => {
        console.log("Hi");
      });
      unlistenTextUpdate = await onTextUpdate((newText) => {
        console.log(newText);
      });
    }

    listenerSetup();

    return () => {
      if (unlistenClipboard) {
        unlistenClipboard();
      }
      if (unlistenImageUpdate) {
        unlistenImageUpdate();
      }
    };
  }, []);

  return <div>ImagesView</div>;
};

export default ImagesView;
```

I am a hundred percent sure, there is something that I am messing up. Tried your demo svelete example app and it works beuatifully. 

Please let me know if i can add any other info here that can help me with this

**Comment by skrewby** [comment]
I had the same issue. It behaves as expected when copying text from outside the application but copying the text displayed inside the app like from a h1 causes a freeze and a crash.

By any chance are you on Linux with Wayland as well? I had the issues in my VM with that setup but when I ran on Windows instead, the same code worked fine.

For reference, I have modified your code to be similar to what I was using to test things:
```ts
import { UnlistenFn } from "@tauri-apps/api/event";
import { useEffect, useState } from "react";
import {
  listenToMonitorStatusUpdate, 
  onClipboardUpdate, 
  onFilesUpdate, 
  onImageUpdate, 
  onTextUpdate, 
  startListening
} from "tauri-plugin-clipboard-api";

const ImagesView = () => {
  const [copiedText, setCopiedText] = useState("Copied text will be here");
  let unlistenTextUpdate: UnlistenFn;
  let unlistenImageUpdate: UnlistenFn;
  let unlistenClipboard: () => Promise<void>;
  let unlistenFiles: UnlistenFn;
  let monitorRunning = false;

useEffect(() => {
    const unlistenFunctions = async () => {
      unlistenTextUpdate = await onTextUpdate((newText) => {
        console.log(newText);
        setCopiedText(newText);
      });
      unlistenImageUpdate = await onImageUpdate((_) => {
        console.log("Image updated");
      });
      unlistenFiles = await onFilesUpdate((_) => {
        console.log("Files updated");
      });
      unlistenClipboard = await startListening();

      onClipboardUpdate(() => {
        console.log("plugin:clipboard://clipboard-monitor/update event received");
      });
    };

    listenToMonitorStatusUpdate((running) => {
      monitorRunning = running; 
    });
    unlistenFunctions().catch(console.error);

    return () => {
      if (unlistenTextUpdate) {
        unlistenTextUpdate();
      }
      if (unlistenImageUpdate) {
        unlistenImageUpdate();
      }
      if (unlistenClipboard) {
        unlistenClipboard();
      }
      if (unlistenFiles) {
        unlistenFiles();
      }
      console.log(monitorRunning);
    };
  }, []);

  return (
    <>
      <h1>Try and copy this sentence</h1>
      <h1>{copiedText}</h1>
    </>
  );
};

export default ImagesView;
```

**Comment by HuakunShen** [comment]
I tried this code https://github.com/CrossCopy/tauri-plugin-clipboard/issues/17#issuecomment-1932421073 on a M1 Mac and worked fine. I also added this example to the examples folder of this repo.
@heysupratim Which OS are you on? Consider trying the new react example, it works for me on Mac.
Note: I tested with the new v0.6.0.

@skrewby I won't have access to Wayland linux until end of Feb. Wayland may not be supported yet. 
I just switched from arboard to [clipboard-rs](https://crates.io/crates/clipboard-rs) to support more clipboard formats, but clipboard-rs doesn't support wayland for now. 

https://crates.io/crates/arboard says, "Wayland works with the X11 protocol just as well", the current version v0.6.0 may work? Could you please try on wayland? 

If not I will try to support Wayland later.

**Comment by skrewby** [comment]
@HuakunShen. I gave a try and updated to 0.6.0 and unfortunately the issue still persists in Wayland. It copies text perfectly except when trying to copy a selection in the app itself. I managed to get the same behaviour with the demo using Svelte. Right now I'm assuming it might be something with WebKit and the X11 protocol in Wayland? 

I cloned tauri-plugin-clipboard and clipboard-rs to test some stuff out and it hangs when calling `get_text()` below

https://github.com/CrossCopy/tauri-plugin-clipboard/blob/ad04bf5da1c085c8a0b001aa876d5cba10b9913a/src/lib.rs#L108-L114

clipboard-rs (and arboard as well) keep looping while polling for events with `ctx.conn.poll_for_event_with_sequence()?` in line 198 below always returning `None` until the request times out or the app crashes.
https://github.com/ChurchTao/clipboard-rs/blob/23a03df52a5a513202e7661e5aa232314341cc1d/src/platform/x11.rs#L198-L204

The debug info doesn't seem to have any red flags but I'm not very experienced with Wayland yet. 
![freeze-copy](https://github.com/CrossCopy/tauri-plugin-clipboard/assets/33297928/2b944fd2-bf15-4868-a6c9-3608b0bf6fea)

I'll investigate a bit more since it's a good excuse to finally learn Wayland but since the majority of the functionality works as expected, it might be one of those things were we just have to wait for Wayland support to solve these more niche cases.

**Comment by HuakunShen** [comment]
@skrewby  Are you saying if you copied text from outside the app, it works on Wayland? Have you tried this on a release build of the app?
How about other formats like image and html?

**Comment by ChurchTao** [comment]
> @HuakunShen. I gave a try and updated to 0.6.0 and unfortunately the issue still persists in Wayland. It copies text perfectly except when trying to copy a selection in the app itself. I managed to get the same behaviour with the demo using Svelte. Right now I'm assuming it might be something with WebKit and the X11 protocol in Wayland?
> 
> I cloned tauri-plugin-clipboard and clipboard-rs to test some stuff out and it hangs when calling `get_text()` below
> 
> https://github.com/CrossCopy/tauri-plugin-clipboard/blob/ad04bf5da1c085c8a0b001aa876d5cba10b9913a/src/lib.rs#L108-L114
> 
> clipboard-rs (and arboard as well) keep looping while polling for events with `ctx.conn.poll_for_event_with_sequence()?` in line 198 below always returning `None` until the request times out or the app crashes. https://github.com/ChurchTao/clipboard-rs/blob/23a03df52a5a513202e7661e5aa232314341cc1d/src/platform/x11.rs#L198-L204
> 
> The debug info doesn't seem to have any red flags but I'm not very experienced with Wayland yet. ![freeze-copy](https://private-user-images.githubusercontent.com/33297928/303711980-2b944fd2-bf15-4868-a6c9-3608b0bf6fea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0OTgyODMsIm5iZiI6MTcwNzQ5Nzk4MywicGF0aCI6Ii8zMzI5NzkyOC8zMDM3MTE5ODAtMmI5NDRmZDItYmYxNS00ODY4LWE2YzktMzYwOGIwYmY2ZmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE2NTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNzgyMWYyNGNmM2I5NWEzMGRjN2M4ZDNlZjBmMWE2ZmExYzFjMmEwYzA5YTc1YzMxNGQzMDE3ZWUyZTRjOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B1QihcgHClITlw9Krfko96MaVeH2YGCr9kqocZOWV88)
> 
> I'll investigate a bit more since it's a good excuse to finally learn Wayland but since the majority of the functionality works as expected, it might be one of those things were we just have to wait for Wayland support to solve these more niche cases.

@skrewby I'll take a look at this question, but the Spring Festival is relatively slow recently. I'll look at it in a few days.

**Comment by skrewby** [comment]
@HuakunShen, it looks like images aren't working with 0.6.0 using the code I posted in an ealier comment. I reverted temporarily to 0.5.5 and ran the release build and took a video to better display the issue

https://github.com/CrossCopy/tauri-plugin-clipboard/assets/33297928/65a912cb-d37b-473a-b464-5eb429452d7f

@ChurchTao Thank you, let me know if you require any more information and I'll do my best to help.

**Comment by ChurchTao** [comment]
@skrewby 
I'm free recently. Could you please provide me with the demo project and operating environment? I'd like to reproduce this problem.

**Comment by skrewby** [comment]
@ChurchTao, apologies for the delay, I created a repo [here](https://github.com/skrewby/clipboard_example) with the example code. After cloning it, you can run it by running `npm install` then `npm run tauri dev`

The issue occurs in any Wayland environment but specifically I was using [Fedora Workstation 39](https://fedoraproject.org/workstation/download)
