### ISSUE TITLE
Tauri v2 support?

### ISSUE THREAD

**Issue by jasonterando** [CrossCopy/tauri-plugin-clipboard#19]
Any plans (or a branch) offering support for the Tauri v2 beta?  Thanks!

**Comment by HuakunShen** [comment]
Planned to support v2 once it's stable.

**Comment by ryusei-48** [comment]
Thank you for developing such a plugin.
I was getting ready to switch from Electron to TAURI.
Electron had a clipboard API, but not the ability to get file pointers, so I had to create my own native C++ extension.
When I switched to TAURI, it seemed that officially only text could be written and read, so now I had to create a module for Rust them, but I found this plugin that helped me.
I am also starting from scratch in learning Rust.

**Comment by HuakunShen** [comment]
@ryusei-48 Glad this plugin helps!

**Comment by HuakunShen** [comment]
I will start working on support for V2, but the official clipboard plugin for Tauri v2 already supports most of the features in this plugin.

**Comment by HuakunShen** [comment]
Tauri v2 now supported. Available on branch `v2`.

**Comment by jasonterando** [comment]
Thanks!  Even though Tauri v2 ostensibly has copy image to clipboard functionality built in, I could not get it to work.  Your plug-in works like a champ!
