### ISSUE TITLE
hasFiles seems to have been removed in the new version of the API, and the demo has not been updated yet.

### ISSUE THREAD

**Issue by Tester-957** [CrossCopy/tauri-plugin-clipboard#27]
Is there an alternative?
![image](https://github.com/CrossCopy/tauri-plugin-clipboard/assets/58334417/f03924dd-8853-491d-8753-0277c593d088)

**Comment by HuakunShen** [comment]
Are you on the latest commit? `hasFiles` is there.
https://github.com/CrossCopy/tauri-plugin-clipboard/blob/fd54d564b8e163cc035e4ee196eeb82458cc1a01/webview-dist/api.d.ts#L51

**Comment by Tester-957** [comment]
> Are you on the latest commit? `hasFiles` is there.
> 
> https://github.com/CrossCopy/tauri-plugin-clipboard/blob/fd54d564b8e163cc035e4ee196eeb82458cc1a01/webview-dist/api.d.ts#L51
Sorry, my problem, I need to clean node_modules and reinstall
