### ISSUE TITLE
Can I writeText and writeHtml at the same time without triggering the event twice?

### ISSUE THREAD

**Issue by Tester-957** [CrossCopy/tauri-plugin-clipboard#28]
I found that when using writeHtml, the html will be written to the clipboard, but the text will not be written. I can understand this. But when the text is copied and writeHtml is used again, the onTextUpdate event will be triggered.

Here are my steps:
1. Control+C to copy arbitrary  text to the clipboard
2. Use the example writeHtml() to write HTML
3. At this time the onClipboardUpdate event contains the text in step 1

Expected results: Step 3 should only listen for hasHTML, not the text from Step 1.🕷️
![image](https://github.com/CrossCopy/tauri-plugin-clipboard/assets/58334417/58eaffea-2074-4ee0-ab59-65ed5e0b9a03)

I think you can add a writeHtmlAndText(html，text) api😉

**Comment by HuakunShen** [comment]
I believe this is because the text from step one is not removed from the UI. So it's not a problem with the API. 
Maybe I can make the example clearer by refreshing all content displayed rather than appending the new clipboard content.
If you take a screenshot after step 3 you will see the text, the html and a screenshot.

**Comment by HuakunShen** [comment]
And in your screenshot has `hasHtml` and `hasText` both equal to true. Are you on Mac?
For me, after writing sample html, I only got `hasHtml == true`
<img width="168" alt="image" src="https://github.com/CrossCopy/tauri-plugin-clipboard/assets/33727687/5dffa30b-37c5-4dc0-90cf-485686e3fc52">

**Comment by Tester-957** [comment]
> And in your screenshot has `hasHtml` and `hasText` both equal to true. Are you on Mac?在您的屏幕截图中， `hasHtml` 和 `hasText` 都等于 true。你在Mac上吗？ For me, after writing sample html, I only got `hasHtml == true` 对我来说，编写示例 html 后，我只得到 `hasHtml == true` <img alt="image" width="168" src="https://private-user-images.githubusercontent.com/33727687/325040722-5dffa30b-37c5-4dc0-90cf-485686e3fc52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDIyOTQsIm5iZiI6MTcxMzk0MTk5NCwicGF0aCI6Ii8zMzcyNzY4Ny8zMjUwNDA3MjItNWRmZmEzMGItMzdjNS00ZGMwLTkwY2YtNDg1Njg2ZTNmYzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA2NTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3N2I3ZmE4ZTIyNzYwNzM4NjRlZTJhYmVjMjI5ZDdiM2M5YTg2MGM0M2E3NTA3ZmE5ZTVlYThiYmMxZmE0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6alcyrhyyDVAm9aO-7iUxHM218r2UsWqDobzhfGMQGw">

On Windows 11, confirm that it is the content left by the last text

**Comment by Tester-957** [comment]
> I believe this is because the text from step one is not removed from the UI. So it's not a problem with the API. Maybe I can make the example clearer by refreshing all content displayed rather than appending the new clipboard content. If you take a screenshot after step 3 you will see the text, the html and a screenshot.
> 
> `git pull` the main branch to get the latest commit. [960e6d9](https://github.com/CrossCopy/tauri-plugin-clipboard/commit/960e6d90a438bb3606549ccede92027e14bb7042)
> 
> Not sure if this is what you want.

When I copy HTML content on Windows, HTML and text will be triggered at the same time, such as copying code in VSCode. I want to be able to write both HTML and text to the clipboard in the same way. This may be a Windows mechanism that allows multiple types of text to exist in the clipboard.

**Comment by HuakunShen** [comment]
@Tester-957 I see what you mean. This needs to be added in clipboard-rs. @ChurchTao

Here is my experiment with cilpboard-rs, writing html doesn't update text.

```rust
let ctx = ClipboardContext::new().unwrap();

ctx.set_html("<h1>hello</h1>".to_string()).unwrap();
let txt = ctx.get_text().unwrap();
println!("txt: {:?}", txt);
let html = ctx.get_html().unwrap();
println!("html: {:?}", html);
```

Output:

```
txt: ""
html: "<h1>hello</h1>"
```

**Comment by HuakunShen** [comment]
A `writeHtmlAndText()` is added.

**Comment by Tester-957** [comment]
> A `writeHtmlAndText()` is added. 添加了 `writeHtmlAndText()` 。

Thank you

**Comment by HuakunShen** [comment]
Oh looks like the new api only worked on Mac, but not windows.

**Comment by HuakunShen** [comment]
Text has to go before Html, otherwise it won't work on Windows.

![image](https://github.com/CrossCopy/tauri-plugin-clipboard/assets/33727687/bbf007be-16a6-4d6f-a9cd-bb015d6c71da)
Fixed in https://github.com/CrossCopy/tauri-plugin-clipboard/releases/tag/v0.6.8

Tested on Mac, Win11, and Ubuntu 22.
