### ISSUE TITLE
Some problems with copying images

### ISSUE THREAD

**Issue by ayangweb** [CrossCopy/tauri-plugin-clipboard#31]
Hey 👋, I searched for a random image from my browser and copied the image, but it triggered the `onHTMLUpdate` event at the same time! Can this be optimized? It should only trigger the `onImageUpdate` event!

<img width="1030" alt="image" src="https://github.com/CrossCopy/tauri-plugin-clipboard/assets/75017711/55366e5f-6930-46fe-bd77-2271c1002ad1">

**Comment by HuakunShen** [comment]
This is the same as your other issue https://github.com/CrossCopy/tauri-plugin-clipboard/issues/32

Copying image from browser indeed triggers both html and image update. 

I will add an option argument. For now you can implement your own listen function.

**Comment by ayangweb** [comment]
> This is the same as your other issue #32
> 
> Copying image from browser indeed triggers both html and image update.
> 
> I will add an option argument. For now you can implement your own listen function.

Okay, thanks.

**Comment by HuakunShen** [comment]
In `v1.0.1` I added a `onSomethingUpdate()` listener. 

```ts
await onSomethingUpdate(async (updatedTypes) => {
	console.log('updated types:', updatedTypes);
	if (updatedTypes.html) {
		console.log(await readHtml());
	}
	if (updatedTypes.image) {
		const img = await readImageBase64()
	}
});
```

You will get `{files: false, image: false, html: true, rtf: false, text: true}` when you copy html and `{files: false, image: true, html: true, rtf: false, text: false}` when you copy image in web page.

Do not call `onHTMLUpdate`. Instead, read the content within the callback.

**Comment by ayangweb** [comment]
> 我`v1.0.1`添加了一个`onSomethingUpdate()`听众。
> 
> ```ts
> await onSomethingUpdate(async (updatedTypes) => {
> 	console.log('updated types:', updatedTypes);
> 	if (updatedTypes.html) {
> 		console.log(await readHtml());
> 	}
> 	if (updatedTypes.image) {
> 		const img = await readImageBase64()
> 	}
> });
> ```
> 
> `{files: false, image: false, html: true, rtf: false, text: true}`当您复制 html 和`{files: false, image: true, html: true, rtf: false, text: false}`复制网页中的图像时，您将获得。
> 
> 不要调用`onHTMLUpdate`。而是读取回调中的内容。

Thanks author, I'll try it later, I'll be out here for a while! Thanks for your hard work.

**Comment by ayangweb** [comment]
> In `v1.0.1` I added a `onSomethingUpdate()` listener.
> 
> ```ts
> await onSomethingUpdate(async (updatedTypes) => {
> 	console.log('updated types:', updatedTypes);
> 	if (updatedTypes.html) {
> 		console.log(await readHtml());
> 	}
> 	if (updatedTypes.image) {
> 		const img = await readImageBase64()
> 	}
> });
> ```
> 
> You will get `{files: false, image: false, html: true, rtf: false, text: true}` when you copy html and `{files: false, image: true, html: true, rtf: false, text: false}` when you copy image in web page.
> 
> Do not call `onHTMLUpdate`. Instead, read the content within the callback.

I tried this and it does work, but I'm curious to ask Does `rtf` mean rich text? What would it be triggered on?
