### ISSUE TITLE
Some problems with copying HTML fragments

### ISSUE THREAD

**Issue by ayangweb** [CrossCopy/tauri-plugin-clipboard#32]
Hey 👋, the `onTextUpdate` event is triggered at the same time when copying the HTML content, is it possible to trigger only the `onHTMLUpdate` event!

<img width="1030" alt="image" src="https://github.com/CrossCopy/tauri-plugin-clipboard/assets/75017711/c880d49c-6d53-475b-bd83-35516e966b3f">

**Comment by HuakunShen** [comment]
That's actually the intended behaviour. Copying HTML write two types of content to your clipboard. 

For now, you could write your own custom listenToClipboard function https://github.com/CrossCopy/tauri-plugin-clipboard/blob/a45bd763571c1924feb7ef0fcef857fef8ad2927/webview-src/api.ts#L256

If you return when HTML is detected, text event won't be triggered.

I will consider adding options to this function.

**Comment by ayangweb** [comment]
> That's actually the intended behaviour. Copying HTML write two types of content to your clipboard.
> 
> For now, you could write your own custom listenToClipboard function
> 
> https://github.com/CrossCopy/tauri-plugin-clipboard/blob/a45bd763571c1924feb7ef0fcef857fef8ad2927/webview-src/api.ts#L256-L259
> 
> If you return when HTML is detected, text event won't be triggered.
> 
> I will consider adding options to this function.

Okay, thanks, I'll try this code

**Comment by HuakunShen** [comment]
Just added a `breakOnType` option for `startListening()` and `listenToCliipboard()`. Published version v1.0.0.

If you do this, text events will not be emited.

```ts
startListening({html: true})
```

- https://crosscopy.github.io/tauri-plugin-clipboard/functions/listenToClipboard.html
- https://crosscopy.github.io/tauri-plugin-clipboard/functions/startListening.html
- https://crosscopy.github.io/tauri-plugin-clipboard/variables/BreakOnType-1.html

**Comment by ayangweb** [comment]
> Just added a `breakOnType` option for `startListening()` and `listenToCliipboard()`. Published version v1.0.0.
> 
> If you do this, text events will not be emited.
> 
> ```ts
> startListening({html: true})
> ```
> 
> * https://crosscopy.github.io/tauri-plugin-clipboard/functions/listenToClipboard.html
> * https://crosscopy.github.io/tauri-plugin-clipboard/functions/startListening.html
> * https://crosscopy.github.io/tauri-plugin-clipboard/variables/BreakOnType-1.html

Okay, thanks. I'll try it later.

**Comment by HuakunShen** [comment]
@ayangweb 
Sorry I just removed the `breakOnType` feature. It's not robust enough. 

A new listener `onSomethingUpdate` is added. I recommend using this to listen for what types of content is updated, then decide which type to read yourself.

Discussed in https://github.com/CrossCopy/tauri-plugin-clipboard/issues/31

**Comment by ayangweb** [comment]
> @ayangweb Sorry I just removed the `breakOnType` feature. It's not robust enough.
> 
> A new listener `onSomethingUpdate` is added. I recommend using this to listen for what types of content is updated, then decide which type to read yourself.
> 
> Discussed in #31 

Okay, thank you author, hard work!
