### ISSUE TITLE
Copy text and images at the same time

### ISSUE THREAD

**Issue by ayangweb** [CrossCopy/tauri-plugin-clipboard#33]
Hey 👋, and then copying the combined text+image message at the same time only triggers the `onFilesUpdate` event? I'm not quite sure if this is a bug or not?

<img width="237" alt="image" src="https://github.com/CrossCopy/tauri-plugin-clipboard/assets/75017711/3bfb55d8-a104-4605-b203-58f0ad90e134">

<img width="1031" alt="image" src="https://github.com/CrossCopy/tauri-plugin-clipboard/assets/75017711/00a43a55-3fa3-4081-944b-f1761c3847e4">

**Comment by HuakunShen** [comment]
How are you copying in QQ? Right click the message and copy? Or right click on image and copy?

**Comment by ayangweb** [comment]
> How are you copying in QQ? Right click the message and copy? Or right click on image and copy?

Right clicking on a blank space and copying it, then pasting it into the chat box again has both text and image, but only triggers the `onFilesUpdate` event!

<img width="619" alt="image" src="https://github.com/CrossCopy/tauri-plugin-clipboard/assets/75017711/b0ddbec0-c0ee-47d7-ac5f-69d393251d57">

**Comment by HuakunShen** [comment]
This is not a problem with this library. It depends on QQ's implementation. 
I reproduced your issue. 
Try pasting to other apps like WeChat or Word document. Only the image will be pasted. 
I guess QQ has a internal storage for what is copied. When you paste within QQ, it pulls from the internal clipboard instead of the system clipboard (That's just a guess).

But there is nothing I can do if the system clipboard isn't really updated.

**Comment by ayangweb** [comment]
> This is not a problem with this library. It depends on QQ's implementation. I reproduced your issue. Try pasting to other apps like WeChat or Word document. Only the image will be pasted. I guess QQ has a internal storage for what is copied. When you paste within QQ, it pulls from the internal clipboard instead of the system clipboard (That's just a guess).
> 
> But there is nothing I can do if the system clipboard isn't really updated.
> 
> Closed for now.

OK, I tested the same thing and it's fine, this should be a feature implemented internally in this kind of apps that support combo messages and has nothing to do with the system clipboard!
