### ISSUE TITLE
How should rtf replication be tested?

### ISSUE THREAD

**Issue by ayangweb** [CrossCopy/tauri-plugin-clipboard#36]
Hey👋, does rtf mean markdown? How can it be triggered? Why can't I trigger it on my end?

**Comment by HuakunShen** [comment]
RTF means Rich Text Format. Mardown is plain text.
If you are on Mac, copy something from pages app will trigger RTF update.
Or copy something from google doc.

**Comment by ayangweb** [comment]
> RTF means Rich Text Format. Mardown is plain text. If you are on Mac, copy something from pages app will trigger RTF update. Or copy something from google doc.

After a lot of testing, my side always triggers html and not rtf.

**Comment by HuakunShen** [comment]
what are you trying to do? html should also contain style information.

**Comment by ayangweb** [comment]
> what are you trying to do? html should also contain style information.

I just want to test out the scenarios in which rtf can be triggered, and it doesn't matter if it doesn't, html is enough.

**Comment by HuakunShen** [comment]
For me it can be tirggerred in pages, html is triggerred at the same time.

**Comment by ayangweb** [comment]
> For me it can be tirggerred in pages, html is triggerred at the same time.


https://github.com/CrossCopy/tauri-plugin-clipboard/assets/75017711/d2135bb9-5602-400c-88ac-67ddd37071ae

It's weird. It's not triggering on my end.

**Comment by ayangweb** [comment]
> For me it can be tirggerred in pages, html is triggerred at the same time.

https://github.com/CrossCopy/tauri-plugin-clipboard/assets/75017711/ad61aa9b-fe69-492b-a053-5b308dff80be

Unfortunately, it doesn't trigger.

**Comment by HuakunShen** [comment]
You are copying web page, which doesn't trigger rtf. Copy from google docs and office word. And when I say pages, I mean https://www.apple.com/ca/pages/

**Comment by ayangweb** [comment]
> You are copying web page, which doesn't trigger rtf. Copy from google docs and office word. And when I say pages, I mean https://www.apple.com/ca/pages/

Ok, thanks, I'll look into it next!
