### ISSUE TITLE
Why is there a `readFiles` method but not a `writeFiles` method?

### ISSUE THREAD

**Issue by ayangweb** [CrossCopy/tauri-plugin-clipboard#37]
Hey👋, Why is there a `readFiles` method but not a `writeFiles` method? Did you forget to add it, or are there other considerations?😁

**Comment by HuakunShen** [comment]
https://crosscopy.github.io/tauri-plugin-clipboard/functions/writeFilesURIs.html

There is.

**Comment by ayangweb** [comment]
> https://crosscopy.github.io/tauri-plugin-clipboard/functions/writeFilesURIs.html
> 
> There is.

Yes, I know there are `readFilesURIs` and `writeFilesURIs`, but the path to `readFilesURIs` can only be read by removing the file:// prefix on MacOS when using tauri-plugin-fs-extra's [metadata](https://github.com/tauri- apps/tauri-plugin-fs-extra) on MacOS, you can only read the information by removing the file:// prefix! `readFiles` is perfectly compatible with both MacOS and Windows, but there is no `writeFiles` method!

<img width="1030" alt="image" src="https://github.com/CrossCopy/tauri-plugin-clipboard/assets/75017711/5d561a19-2bb6-4eec-a1a4-d68684035a89">

<img width="1030" alt="image" src="https://github.com/CrossCopy/tauri-plugin-clipboard/assets/75017711/500eebc3-1dad-436b-8beb-82c9f46287c9">

**Comment by HuakunShen** [comment]
The reason is they are too similar. uri is simply file path with `file://` prefix on unix based system and no difference on windows. I added `writeFiles` in the latest release.

**Comment by ayangweb** [comment]
> The reason is they are too similar. uri is simply file path with `file://` prefix on unix based system and no difference on windows. I added `writeFiles` in the latest release.

Ok, thanks, I don't know linux, but in macOS and Windows, as far as I've come across so far, removing `file://` is perfectly adequate! 😁
