### ISSUE TITLE
About inserting content directly into the app

### ISSUE THREAD

**Issue by ayangweb** [CrossCopy/tauri-plugin-clipboard#38]
Hey 👋, I want to insert the contents of my clipboard directly into the app, do you have a good suggestion? Thanks for the answer!😁

**Comment by HuakunShen** [comment]
Can you elaborate this question? What app and what kind of insert?

**Comment by HuakunShen** [comment]
Use rdev

**Comment by ayangweb** [comment]
> Use rdev

Okay, I'll look into it! Thanks!
