### ISSUE TITLE
invalid args `rtfContent` for command `write_rtf`: command write_rtf missing required key rtfContent

### ISSUE THREAD

**Issue by ryusei-48** [CrossCopy/tauri-plugin-clipboard#39]
Hello. This plugin is very useful.
When I call the `writeRtf()` method in front side TypeScript and try to write RTF format data to the clipboard, the following Promise error is printed to the console.
```command
Uncaught (in promise) invalid args `rtfContent` for command `write_rtf`: command write_rtf missing required key rtfContent
```
It appears that there is an error in the backend command.
Is it possible to fix the bug here?

## environment
TAURI v1.6.8
tauri-plugin-clipboard v1.1.0
tauri-plugin-clipboard-api v1.0.1

Thank you very much.

**Comment by HuakunShen** [comment]
Thank you for pointing this out. It's fixed. Try upgrade to v1.1.1

**Comment by ryusei-48** [comment]
The response was fast and helpful.
Thank you very much.
