### ISSUE TITLE
After the Tauri beta v2 update, the addition of the Emitter trait caused a compilation error

### ISSUE THREAD

**Issue by kui04** [CrossCopy/tauri-plugin-clipboard#40]
Hi. Thank you for developing this plugin.

The recent [update](https://github.com/tauri-apps/tauri/pull/9640) in the Tauri repository introduced the `Emitter` trait, which caused a compilation error. This can be fixed by simply importing the `Emitter` trait.

![QQ_1720874283847](https://github.com/user-attachments/assets/6d92ed95-233b-4429-b3f3-6dd20ab4c411)

**Comment by HuakunShen** [comment]
Thank you for letting me know. Should now be fixed in v2.1.3. 
Supports latest Tauri v2.0.0-beta.24
