### ISSUE TITLE
佬，考虑加一个读取图片保存到本地的功能吗？

### ISSUE THREAD

**Issue by ayangweb** [CrossCopy/tauri-plugin-clipboard#42]
佬，考虑新增一个读取图片的方法，然后可以传入存储图片的路径，这样就只需要将图片保存到本地，然后直接可以访问了，如果考虑的话，我想蹭个 pr🌹

**Comment by HuakunShen** [comment]
不太理解，请详细描述使用场景和用法

**Comment by ayangweb** [comment]
佬，看 https://github.com/ayangweb/EcoPaste/blob/213e448b70a17daea96ff8eaa99204b77474b109/src-tauri/src/plugins/clipboard.rs#L152 这个，大概这个意思🌹

**Comment by ayangweb** [comment]
我的代码没做 err 处理，还是使用您的插件会比较方便些🤣

**Comment by HuakunShen** [comment]
相当于读截图后返回的不是图片数据而是文件路径？目的是什么？

**Comment by ayangweb** [comment]
对的🌹，这个速度会明显快很多

**Comment by HuakunShen** [comment]
这个逻辑写一个rust command调用tauri-plugin-clipboard就好了吧，如果要把这个command加到plugin里还需要考虑清理cache的情况。还有缓存在硬盘上是存原图还是thumbnail也是很自定义的事，应该放在app里完成而不是plugin里。

**Comment by ayangweb** [comment]
> 这个逻辑写一个rust command调用tauri-plugin-clipboard就好了吧，如果要把这个command加到plugin里还需要考虑清理cache的情况。还有缓存在硬盘上是存原图还是thumbnail也是很自定义的事，应该放在app里完成而不是plugin里。

哈哈，也对哈，这个应该自定义的哈🫣我加下容错，我写的报错有点多，哈哈🤣

**Comment by HuakunShen** [comment]
看到你写的EcoPaste很不错有兴趣认识下吗

**Comment by ayangweb** [comment]
可以啊，大佬，加个微信咩🫣

**Comment by HuakunShen** [comment]
我的profile里有email你可以发给我我加你
