### ISSUE TITLE
建议升级包版本

### ISSUE THREAD

**Issue by ChurchTao** [CrossCopy/tauri-plugin-clipboard#43]
https://github.com/CrossCopy/tauri-plugin-clipboard/blob/c3f8ec345f9e3bb03ec36df7176f1aca358433b3/Cargo.toml#L19

这边建议升级到  `0.1.11`

修了windows 上面图片的读写有一些问题，Linux上有个无限循环卡死的问题

**Comment by HuakunShen** [comment]
谢谢，已经更新
https://github.com/CrossCopy/tauri-plugin-clipboard/releases/tag/1.1.4
