### ISSUE TITLE
Doesn't work on Deno

### ISSUE THREAD

**Issue by justinmchase** [CrossCopy/tauri-plugin-clipboard#52]
This repo has published into https://jsr.io but if I follow the typescript example when running on Deno it just says

> window not found

Which of course it doesn't exist in Deno.

**Comment by HuakunShen** [comment]
First of all, on JSR I didn't enable Deno compatibility.
And this package is supposed to be run in a webview window to communicate with tauri core.
It should not be used in Deno runtime.

**Comment by justinmchase** [comment]
![Screenshot 2024-12-23 at 3 43 02 PM](https://github.com/user-attachments/assets/c11aed86-c02a-474d-b130-6995bd662300)

**Comment by HuakunShen** [comment]
You should look at the “works with” part above this button. I can’t control the installation button , it’s always there.

**Comment by justinmchase** [comment]
Ok, I'll close this but I was assuming since it was rust it was compiling to wasm and being loaded with ffi, which deno supports. Theoretically this should be able to work without the window when running in deno but I haven't dug in that deeply yet.

**Comment by HuakunShen** [comment]
No, this is a plugin for tauri, the js part only runs in browser to communicate with the core process written in rust. You can find my video talking about plugin on YouTube.

**Comment by HuakunShen** [comment]
Do you know what tauri is? If you are trying to access clipboard data with deno, then this plugin is not for you.
you could try https://github.com/CrossCopy/clipboard

**Comment by HuakunShen** [comment]
BTW, you can install the package with deno as a package manager, but not as a runtime. 
e.g. If you are running react dev server with deno, then it's OK to install the package with Deno, but the package's JS code still runs in browser.
