### ISSUE TITLE
tauri-plugin-clipboard change clipboard monitor method to clipboard-master library

### ISSUE THREAD

**Issue by HuakunShen** [CrossCopy/tauri-plugin-clipboard#7]
Currently clipboard monitoring was achieved by reading clipboard data in JS repeatedly and checking equality. This is not efficient, especially when this happens in browser/JS (single thread) which could slow down the app.

I want to move the hard work to rust, preferably using https://crates.io/crates/clipboard-master

**Comment by Don-Cryptus** [comment]
yes the clipboard master library is really good I am implementing it on my own clipboard manager https://github.com/Don-Cryptus/clippy until you have it changed I have to sadly use it with my own implementation

**Comment by HuakunShen** [comment]
clipboard-master integrated in PR https://github.com/CrossCopy/tauri-plugin-clipboard/issues/8

@don-cryptus
